name: 'automated_testing_framework_plugin_connectivity'
description: 'Library to use provide connectivity related test steps to the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_connectivity'
version: '4.0.1'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  automated_testing_framework: '^5.0.0'
  connectivity_plus: '^3.0.2'
  convert: '^3.1.1'
  flutter:
    sdk: 'flutter'
  form_validation: '^2.2.0+6'
  json_class: '^2.1.4+1'
  logging: '^1.1.0'
  static_translations: '^2.1.1+22'

dev_dependencies:
  flutter_test:
    sdk: 'flutter'

flutter:
  uses-material-design: true

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
