name: 'automated_testing_framework_plugin_connectivity'
description: 'Library to use provide connectivity related test steps to the Automated Testing Framework.'
homepage: 'https://github.com/peiffer-innovations/automated_testing_framework_plugin_connectivity'
version: '4.0.0+6'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  automated_testing_framework: '^4.0.1+7'
  connectivity_plus: '^2.3.5'
  convert: '^3.0.2'
  flutter: 
    sdk: 'flutter'
  form_validation: '^2.1.0+8'
  json_class: '^2.1.2+7'
  logging: '^1.0.2'
  static_translations: '^2.1.1+5'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true
