name: automated_testing_framework_plugin_connectivity
description: Library to use provide connectivity related test steps to the Automated Testing Framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_connectivity

version: 3.0.4+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.3.1+1
  connectivity_plus: ^2.3.0
  convert: ^3.0.1
  flutter:
    sdk: flutter
  form_validation: ^2.1.0+2
  json_class: ^2.1.2+4
  logging: ^1.0.2
  static_translations: ^2.1.1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
