name: automated_testing_framework_plugin_connectivity
description: Library to use provide connectivity related test steps to the Automated Testing Framework.
homepage: https://github.com/peiffer-innovations/automated_testing_framework_plugin_connectivity

version: 3.0.2+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  automated_testing_framework: ^3.1.0+3
  connectivity: ^3.0.6
  convert: ^3.0.1
  flutter:
    sdk: flutter
  form_validation: ^2.0.0
  json_class: ^2.0.0+1
  logging: ^1.0.2
  static_translations: ^2.0.2+1

# dependency_overrides:
#   automated_testing_framework:
#     path: ../automated_testing_framework
#   automated_testing_framework_models:
#     path: ../automated_testing_framework_models

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
